[package]
name = "blueprint-rs"
version = "0.1.0"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2"
yew = "0.17"
web-sys = "0.3"

[build-dependencies]
regex = { version = "1", default-features = false, features = ["std"] }
heck = "0.3"
