[build]
publish = "public"
command = "curl -sSL https://sh.rustup.rs | sh -s -- -q -y && export PATH=$HOME/.cargo/bin:$PATH && curl -sSL https://github.com/rustwasm/wasm-pack/releases/download/v0.9.1/wasm-pack-v0.9.1-x86_64-unknown-linux-musl.tar.gz | tar xzO wasm-pack-v0.9.1-x86_64-unknown-linux-musl/wasm-pack > /usr/local/bin/wasm-pack && chmod +x /usr/local/bin/wasm-pack && ./build.sh"
